/**
 * Zweiffel competition calendar (fixture dates are 2026–27).
 * Loaded into the **active** season alongside National / Flanders / Wallonia.
 * Divisions: Honneur, 1, 2A, 2B, APM 1, APM 2 (one group each).
 * Renames applied: Div1 7F Gilles→Dekandelaer; Div2A 7F Debaeke→Gilles.
 */

export const ZWEIFFEL_DIVISION_NAMES = [
  "Honneur",
  "1",
  "2A",
  "2B",
  "APM 1",
  "APM 2",
] as const;

export type ZweiffelDivisionName = (typeof ZWEIFFEL_DIVISION_NAMES)[number];

export type ZweiffelFixtureRow = {
  round: number;
  home: string;
  away: string;
};

export type ZweiffelRoundSlot = {
  round: number;
  date: string;
  time: string;
};

export type ZweiffelDivisionSpec = {
  name: ZweiffelDivisionName;
  divisionLevelCode: "first" | "second" | "third";
  teams: string[];
  fixtures: ZweiffelFixtureRow[];
  rounds: ZweiffelRoundSlot[];
  roundRobinCount: number;
  roundCount: number;
};

/** Team label → federation club_number (shared DB / Ledenbeheer). */
export const ZWEIFFEL_TEAM_CLUB_NUMBERS: Record<string, string> = {
  "7F Barroy": "201107",
  "7F Dekandelaer": "201107",
  "7F Gilles": "201107",
  "7F de Bussche": "201107",
  "ARG De Schryver": "201080",
  "ARG Hocq": "201080",
  "ARG Van Assche": "201080",
  "ARG Vandendries": "201080",
  "ASUB Jossaer": "201064",
  "ASUB Pletser": "201064",
  "ASUB Rittweger": "201064",
  "ASUB Stuyck": "201064",
  "BBC Castille": "201014",
  "BBC Chif": "201014",
  "BBC Claes": "201014",
  "BBC Dehaye": "201014",
  "BBC Deleval": "201014",
  "BBC Gigot": "201014",
  "BBC Huntz": "201014",
  "BBC Jourdain": "201014",
  "BBC Kaplan": "201014",
  "BBC Louveaux": "201014",
  "BBC Oldenhove": "201014",
  "BBC Ortegat": "201014",
  "BBC Roosels": "201014",
  "BBC Steed": "201014",
  "BBC Thys": "201014",
  "BBC Valentin": "201014",
  "BBC VandenHove": "201014",
  "BBC Wauters": "201014",
  "BNPPF Duhoux": "201058",
  "BNPPF Wilbaux": "201058",
  "Hirondelle Huegaerts": "201068",
  "Parilasne Van Parijs": "201086",
  "Primerose Gilles": "201092",
  "Smohain": "201070",
  "Star 65 Deyaert": "201003",
  "WBC Dufrasne": "201108",
  "WBC Ramaekers": "201108",
  "Wavre Koscielniak": "201066",
};

export function isByeLabel(label: string | null | undefined): boolean {
  return (label ?? "").trim().toLowerCase() === "bye";
}

export function zweiffelSlotToBrusselsLocal(slot: ZweiffelRoundSlot): string {
  return `${slot.date}T${slot.time}`;
}

export function uniqueZweiffelClubNumbers(): string[] {
  return [...new Set(Object.values(ZWEIFFEL_TEAM_CLUB_NUMBERS))].sort();
}

export const ZWEIFFEL_DIVISION_SPECS: ZweiffelDivisionSpec[] = [
  {
    name: "Honneur",
    divisionLevelCode: "first",
    teams: [
      "BBC Dehaye",
      "BBC Wauters",
      "BBC Thys",
      "BBC Huntz",
      "BBC Kaplan",
      "ASUB Pletser",
      "BBC Jourdain",
      "ASUB Stuyck",
    ],
    roundRobinCount: 2,
    roundCount: 14,
    rounds: [
      { round: 1, date: "2026-10-06", time: "20:00" },
      { round: 2, date: "2026-10-13", time: "20:00" },
      { round: 3, date: "2026-11-03", time: "20:00" },
      { round: 4, date: "2026-11-10", time: "20:00" },
      { round: 5, date: "2026-11-17", time: "20:00" },
      { round: 6, date: "2026-12-01", time: "20:00" },
      { round: 7, date: "2026-12-08", time: "20:00" },
      { round: 8, date: "2027-01-05", time: "20:00" },
      { round: 9, date: "2027-01-12", time: "20:00" },
      { round: 10, date: "2027-01-19", time: "20:00" },
      { round: 11, date: "2027-02-09", time: "20:00" },
      { round: 12, date: "2027-02-16", time: "20:00" },
      { round: 13, date: "2027-03-09", time: "20:00" },
      { round: 14, date: "2027-03-16", time: "20:00" },
    ],
    fixtures: [
      { round: 1, home: "BBC Dehaye", away: "BBC Wauters" },
      { round: 1, home: "BBC Thys", away: "BBC Huntz" },
      { round: 1, home: "BBC Kaplan", away: "ASUB Pletser" },
      { round: 1, home: "BBC Jourdain", away: "ASUB Stuyck" },
      { round: 2, home: "ASUB Pletser", away: "BBC Dehaye" },
      { round: 2, home: "BBC Kaplan", away: "BBC Wauters" },
      { round: 2, home: "ASUB Stuyck", away: "BBC Thys" },
      { round: 2, home: "BBC Huntz", away: "BBC Jourdain" },
      { round: 3, home: "BBC Jourdain", away: "BBC Dehaye" },
      { round: 3, home: "ASUB Pletser", away: "BBC Wauters" },
      { round: 3, home: "BBC Kaplan", away: "BBC Thys" },
      { round: 3, home: "ASUB Stuyck", away: "BBC Huntz" },
      { round: 4, home: "BBC Dehaye", away: "ASUB Stuyck" },
      { round: 4, home: "BBC Wauters", away: "BBC Jourdain" },
      { round: 4, home: "BBC Thys", away: "ASUB Pletser" },
      { round: 4, home: "BBC Huntz", away: "BBC Kaplan" },
      { round: 5, home: "BBC Huntz", away: "BBC Dehaye" },
      { round: 5, home: "BBC Thys", away: "BBC Wauters" },
      { round: 5, home: "BBC Kaplan", away: "ASUB Stuyck" },
      { round: 5, home: "BBC Jourdain", away: "ASUB Pletser" },
      { round: 6, home: "BBC Dehaye", away: "BBC Thys" },
      { round: 6, home: "BBC Wauters", away: "BBC Huntz" },
      { round: 6, home: "ASUB Stuyck", away: "ASUB Pletser" },
      { round: 6, home: "BBC Jourdain", away: "BBC Kaplan" },
      { round: 7, home: "BBC Kaplan", away: "BBC Dehaye" },
      { round: 7, home: "ASUB Stuyck", away: "BBC Wauters" },
      { round: 7, home: "BBC Jourdain", away: "BBC Thys" },
      { round: 7, home: "ASUB Pletser", away: "BBC Huntz" },
      { round: 8, home: "BBC Wauters", away: "BBC Dehaye" },
      { round: 8, home: "BBC Huntz", away: "BBC Thys" },
      { round: 8, home: "ASUB Pletser", away: "BBC Kaplan" },
      { round: 8, home: "ASUB Stuyck", away: "BBC Jourdain" },
      { round: 9, home: "BBC Dehaye", away: "ASUB Pletser" },
      { round: 9, home: "BBC Wauters", away: "BBC Kaplan" },
      { round: 9, home: "BBC Thys", away: "ASUB Stuyck" },
      { round: 9, home: "BBC Jourdain", away: "BBC Huntz" },
      { round: 10, home: "BBC Dehaye", away: "BBC Jourdain" },
      { round: 10, home: "BBC Wauters", away: "ASUB Pletser" },
      { round: 10, home: "BBC Thys", away: "BBC Kaplan" },
      { round: 10, home: "BBC Huntz", away: "ASUB Stuyck" },
      { round: 11, home: "ASUB Stuyck", away: "BBC Dehaye" },
      { round: 11, home: "BBC Jourdain", away: "BBC Wauters" },
      { round: 11, home: "ASUB Pletser", away: "BBC Thys" },
      { round: 11, home: "BBC Kaplan", away: "BBC Huntz" },
      { round: 12, home: "BBC Dehaye", away: "BBC Huntz" },
      { round: 12, home: "BBC Wauters", away: "BBC Thys" },
      { round: 12, home: "ASUB Stuyck", away: "BBC Kaplan" },
      { round: 12, home: "ASUB Pletser", away: "BBC Jourdain" },
      { round: 13, home: "BBC Thys", away: "BBC Dehaye" },
      { round: 13, home: "BBC Huntz", away: "BBC Wauters" },
      { round: 13, home: "ASUB Pletser", away: "ASUB Stuyck" },
      { round: 13, home: "BBC Kaplan", away: "BBC Jourdain" },
      { round: 14, home: "BBC Dehaye", away: "BBC Kaplan" },
      { round: 14, home: "BBC Wauters", away: "ASUB Stuyck" },
      { round: 14, home: "BBC Thys", away: "BBC Jourdain" },
      { round: 14, home: "BBC Huntz", away: "ASUB Pletser" },
    ],
  },
  {
    name: "1",
    divisionLevelCode: "first",
    teams: [
      "BBC Chif",
      "BBC VandenHove",
      "BBC Valentin",
      "BBC Louveaux",
      "Parilasne Van Parijs",
      "ASUB Jossaer",
      "7F Dekandelaer",
      "BBC Claes",
    ],
    roundRobinCount: 2,
    roundCount: 14,
    rounds: [
      { round: 1, date: "2026-10-06", time: "20:00" },
      { round: 2, date: "2026-10-13", time: "20:00" },
      { round: 3, date: "2026-11-03", time: "20:00" },
      { round: 4, date: "2026-11-10", time: "20:00" },
      { round: 5, date: "2026-11-17", time: "20:00" },
      { round: 6, date: "2026-12-01", time: "20:00" },
      { round: 7, date: "2026-12-08", time: "20:00" },
      { round: 8, date: "2027-01-05", time: "20:00" },
      { round: 9, date: "2027-01-12", time: "20:00" },
      { round: 10, date: "2027-01-19", time: "20:00" },
      { round: 11, date: "2027-02-09", time: "20:00" },
      { round: 12, date: "2027-02-16", time: "20:00" },
      { round: 13, date: "2027-03-09", time: "20:00" },
      { round: 14, date: "2027-03-16", time: "20:00" },
    ],
    fixtures: [
      { round: 1, home: "BBC Chif", away: "BBC VandenHove" },
      { round: 1, home: "BBC Valentin", away: "BBC Louveaux" },
      { round: 1, home: "Parilasne Van Parijs", away: "ASUB Jossaer" },
      { round: 1, home: "7F Dekandelaer", away: "BBC Claes" },
      { round: 2, home: "ASUB Jossaer", away: "BBC VandenHove" },
      { round: 2, home: "Parilasne Van Parijs", away: "BBC Chif" },
      { round: 2, home: "BBC Valentin", away: "7F Dekandelaer" },
      { round: 2, home: "BBC Louveaux", away: "BBC Claes" },
      { round: 3, home: "BBC Claes", away: "BBC VandenHove" },
      { round: 3, home: "ASUB Jossaer", away: "BBC Chif" },
      { round: 3, home: "Parilasne Van Parijs", away: "BBC Valentin" },
      { round: 3, home: "BBC Louveaux", away: "7F Dekandelaer" },
      { round: 4, home: "7F Dekandelaer", away: "BBC VandenHove" },
      { round: 4, home: "BBC Chif", away: "BBC Claes" },
      { round: 4, home: "BBC Valentin", away: "ASUB Jossaer" },
      { round: 4, home: "BBC Louveaux", away: "Parilasne Van Parijs" },
      { round: 5, home: "BBC Louveaux", away: "BBC VandenHove" },
      { round: 5, home: "BBC Valentin", away: "BBC Chif" },
      { round: 5, home: "Parilasne Van Parijs", away: "7F Dekandelaer" },
      { round: 5, home: "BBC Claes", away: "ASUB Jossaer" },
      { round: 6, home: "BBC VandenHove", away: "BBC Valentin" },
      { round: 6, home: "BBC Chif", away: "BBC Louveaux" },
      { round: 6, home: "7F Dekandelaer", away: "ASUB Jossaer" },
      { round: 6, home: "BBC Claes", away: "Parilasne Van Parijs" },
      { round: 7, home: "Parilasne Van Parijs", away: "BBC VandenHove" },
      { round: 7, home: "7F Dekandelaer", away: "BBC Chif" },
      { round: 7, home: "BBC Claes", away: "BBC Valentin" },
      { round: 7, home: "ASUB Jossaer", away: "BBC Louveaux" },
      { round: 8, home: "BBC VandenHove", away: "BBC Chif" },
      { round: 8, home: "BBC Louveaux", away: "BBC Valentin" },
      { round: 8, home: "ASUB Jossaer", away: "Parilasne Van Parijs" },
      { round: 8, home: "BBC Claes", away: "7F Dekandelaer" },
      { round: 9, home: "BBC VandenHove", away: "ASUB Jossaer" },
      { round: 9, home: "BBC Chif", away: "Parilasne Van Parijs" },
      { round: 9, home: "7F Dekandelaer", away: "BBC Valentin" },
      { round: 9, home: "BBC Claes", away: "BBC Louveaux" },
      { round: 10, home: "BBC VandenHove", away: "BBC Claes" },
      { round: 10, home: "BBC Chif", away: "ASUB Jossaer" },
      { round: 10, home: "BBC Valentin", away: "Parilasne Van Parijs" },
      { round: 10, home: "7F Dekandelaer", away: "BBC Louveaux" },
      { round: 11, home: "BBC VandenHove", away: "7F Dekandelaer" },
      { round: 11, home: "BBC Claes", away: "BBC Chif" },
      { round: 11, home: "ASUB Jossaer", away: "BBC Valentin" },
      { round: 11, home: "Parilasne Van Parijs", away: "BBC Louveaux" },
      { round: 12, home: "BBC VandenHove", away: "BBC Louveaux" },
      { round: 12, home: "BBC Chif", away: "BBC Valentin" },
      { round: 12, home: "7F Dekandelaer", away: "Parilasne Van Parijs" },
      { round: 12, home: "ASUB Jossaer", away: "BBC Claes" },
      { round: 13, home: "BBC Valentin", away: "BBC VandenHove" },
      { round: 13, home: "BBC Louveaux", away: "BBC Chif" },
      { round: 13, home: "ASUB Jossaer", away: "7F Dekandelaer" },
      { round: 13, home: "Parilasne Van Parijs", away: "BBC Claes" },
      { round: 14, home: "BBC VandenHove", away: "Parilasne Van Parijs" },
      { round: 14, home: "BBC Chif", away: "7F Dekandelaer" },
      { round: 14, home: "BBC Valentin", away: "BBC Claes" },
      { round: 14, home: "BBC Louveaux", away: "ASUB Jossaer" },
    ],
  },
  {
    name: "2A",
    divisionLevelCode: "second",
    teams: [
      "7F Gilles",
      "ARG Van Assche",
      "BBC Steed",
      "BBC Deleval",
      "Primerose Gilles",
      "Star 65 Deyaert",
    ],
    roundRobinCount: 3,
    roundCount: 15,
    rounds: [
      { round: 1, date: "2026-10-06", time: "20:00" },
      { round: 2, date: "2026-10-13", time: "20:00" },
      { round: 3, date: "2026-11-03", time: "20:00" },
      { round: 4, date: "2026-11-10", time: "20:00" },
      { round: 5, date: "2026-11-17", time: "20:00" },
      { round: 6, date: "2026-12-01", time: "20:00" },
      { round: 7, date: "2026-12-08", time: "20:00" },
      { round: 8, date: "2027-01-05", time: "20:00" },
      { round: 9, date: "2027-01-12", time: "20:00" },
      { round: 10, date: "2027-01-19", time: "20:00" },
      { round: 11, date: "2027-02-09", time: "20:00" },
      { round: 12, date: "2027-02-16", time: "20:00" },
      { round: 13, date: "2027-02-23", time: "20:00" },
      { round: 14, date: "2027-03-09", time: "20:00" },
      { round: 15, date: "2027-03-16", time: "20:00" },
    ],
    fixtures: [
      { round: 1, home: "7F Gilles", away: "ARG Van Assche" },
      { round: 1, home: "BBC Steed", away: "BBC Deleval" },
      { round: 1, home: "Primerose Gilles", away: "Star 65 Deyaert" },
      { round: 2, home: "BBC Deleval", away: "7F Gilles" },
      { round: 2, home: "ARG Van Assche", away: "Primerose Gilles" },
      { round: 2, home: "Star 65 Deyaert", away: "BBC Steed" },
      { round: 3, home: "Primerose Gilles", away: "7F Gilles" },
      { round: 3, home: "BBC Deleval", away: "Star 65 Deyaert" },
      { round: 3, home: "ARG Van Assche", away: "BBC Steed" },
      { round: 4, home: "7F Gilles", away: "Star 65 Deyaert" },
      { round: 4, home: "BBC Steed", away: "Primerose Gilles" },
      { round: 4, home: "BBC Deleval", away: "ARG Van Assche" },
      { round: 5, home: "BBC Steed", away: "7F Gilles" },
      { round: 5, home: "Star 65 Deyaert", away: "ARG Van Assche" },
      { round: 5, home: "Primerose Gilles", away: "BBC Deleval" },
      { round: 6, home: "ARG Van Assche", away: "7F Gilles" },
      { round: 6, home: "BBC Deleval", away: "BBC Steed" },
      { round: 6, home: "Star 65 Deyaert", away: "Primerose Gilles" },
      { round: 7, home: "7F Gilles", away: "BBC Deleval" },
      { round: 7, home: "Primerose Gilles", away: "ARG Van Assche" },
      { round: 7, home: "BBC Steed", away: "Star 65 Deyaert" },
      { round: 8, home: "Star 65 Deyaert", away: "7F Gilles" },
      { round: 8, home: "Primerose Gilles", away: "BBC Steed" },
      { round: 8, home: "ARG Van Assche", away: "BBC Deleval" },
      { round: 9, home: "7F Gilles", away: "Primerose Gilles" },
      { round: 9, home: "Star 65 Deyaert", away: "BBC Deleval" },
      { round: 9, home: "BBC Steed", away: "ARG Van Assche" },
      { round: 10, home: "7F Gilles", away: "BBC Steed" },
      { round: 10, home: "ARG Van Assche", away: "Star 65 Deyaert" },
      { round: 10, home: "BBC Deleval", away: "Primerose Gilles" },
      { round: 11, home: "BBC Deleval", away: "7F Gilles" },
      { round: 11, home: "ARG Van Assche", away: "Primerose Gilles" },
      { round: 11, home: "Star 65 Deyaert", away: "BBC Steed" },
      { round: 12, home: "7F Gilles", away: "ARG Van Assche" },
      { round: 12, home: "BBC Steed", away: "BBC Deleval" },
      { round: 12, home: "Primerose Gilles", away: "Star 65 Deyaert" },
      { round: 13, home: "Primerose Gilles", away: "7F Gilles" },
      { round: 13, home: "BBC Deleval", away: "Star 65 Deyaert" },
      { round: 13, home: "ARG Van Assche", away: "BBC Steed" },
      { round: 14, home: "7F Gilles", away: "Star 65 Deyaert" },
      { round: 14, home: "BBC Steed", away: "Primerose Gilles" },
      { round: 14, home: "BBC Deleval", away: "ARG Van Assche" },
      { round: 15, home: "BBC Steed", away: "7F Gilles" },
      { round: 15, home: "Star 65 Deyaert", away: "ARG Van Assche" },
      { round: 15, home: "Primerose Gilles", away: "BBC Deleval" },
    ],
  },
  {
    name: "2B",
    divisionLevelCode: "second",
    teams: [
      "Hirondelle Huegaerts",
      "Wavre Koscielniak",
      "ARG Hocq",
      "BBC Gigot",
      "BBC Oldenhove",
      "ASUB Rittweger",
      "ARG De Schryver",
    ],
    roundRobinCount: 2,
    roundCount: 14,
    rounds: [
      { round: 1, date: "2026-10-06", time: "20:00" },
      { round: 2, date: "2026-10-13", time: "20:00" },
      { round: 3, date: "2026-11-03", time: "20:00" },
      { round: 4, date: "2026-11-10", time: "20:00" },
      { round: 5, date: "2026-11-17", time: "20:00" },
      { round: 6, date: "2026-12-01", time: "20:00" },
      { round: 7, date: "2026-12-08", time: "20:00" },
      { round: 8, date: "2027-01-05", time: "20:00" },
      { round: 9, date: "2027-01-12", time: "20:00" },
      { round: 10, date: "2027-01-19", time: "20:00" },
      { round: 11, date: "2027-02-09", time: "20:00" },
      { round: 12, date: "2027-02-16", time: "20:00" },
      { round: 13, date: "2027-03-09", time: "20:00" },
      { round: 14, date: "2027-03-16", time: "20:00" },
    ],
    fixtures: [
      { round: 1, home: "Hirondelle Huegaerts", away: "Bye" },
      { round: 1, home: "Wavre Koscielniak", away: "ARG Hocq" },
      { round: 1, home: "BBC Gigot", away: "BBC Oldenhove" },
      { round: 1, home: "ASUB Rittweger", away: "ARG De Schryver" },
      { round: 2, home: "BBC Oldenhove", away: "Bye" },
      { round: 2, home: "BBC Gigot", away: "Hirondelle Huegaerts" },
      { round: 2, home: "ARG Hocq", away: "ASUB Rittweger" },
      { round: 2, home: "ARG De Schryver", away: "Wavre Koscielniak" },
      { round: 3, home: "ARG De Schryver", away: "Bye" },
      { round: 3, home: "BBC Oldenhove", away: "Hirondelle Huegaerts" },
      { round: 3, home: "BBC Gigot", away: "ARG Hocq" },
      { round: 3, home: "Wavre Koscielniak", away: "ASUB Rittweger" },
      { round: 4, home: "ASUB Rittweger", away: "Bye" },
      { round: 4, home: "Hirondelle Huegaerts", away: "ARG De Schryver" },
      { round: 4, home: "BBC Oldenhove", away: "ARG Hocq" },
      { round: 4, home: "Wavre Koscielniak", away: "BBC Gigot" },
      { round: 5, home: "Wavre Koscielniak", away: "Bye" },
      { round: 5, home: "ARG Hocq", away: "Hirondelle Huegaerts" },
      { round: 5, home: "BBC Gigot", away: "ASUB Rittweger" },
      { round: 5, home: "ARG De Schryver", away: "BBC Oldenhove" },
      { round: 6, home: "Bye", away: "ARG Hocq" },
      { round: 6, home: "Hirondelle Huegaerts", away: "Wavre Koscielniak" },
      { round: 6, home: "ASUB Rittweger", away: "BBC Oldenhove" },
      { round: 6, home: "BBC Gigot", away: "ARG De Schryver" },
      { round: 7, home: "BBC Gigot", away: "Bye" },
      { round: 7, home: "ASUB Rittweger", away: "Hirondelle Huegaerts" },
      { round: 7, home: "ARG De Schryver", away: "ARG Hocq" },
      { round: 7, home: "BBC Oldenhove", away: "Wavre Koscielniak" },
      { round: 8, home: "Bye", away: "Hirondelle Huegaerts" },
      { round: 8, home: "ARG Hocq", away: "Wavre Koscielniak" },
      { round: 8, home: "BBC Oldenhove", away: "BBC Gigot" },
      { round: 8, home: "ARG De Schryver", away: "ASUB Rittweger" },
      { round: 9, home: "Bye", away: "BBC Oldenhove" },
      { round: 9, home: "Hirondelle Huegaerts", away: "BBC Gigot" },
      { round: 9, home: "ASUB Rittweger", away: "ARG Hocq" },
      { round: 9, home: "Wavre Koscielniak", away: "ARG De Schryver" },
      { round: 10, home: "Bye", away: "ARG De Schryver" },
      { round: 10, home: "Hirondelle Huegaerts", away: "BBC Oldenhove" },
      { round: 10, home: "ARG Hocq", away: "BBC Gigot" },
      { round: 10, home: "ASUB Rittweger", away: "Wavre Koscielniak" },
      { round: 11, home: "Bye", away: "ASUB Rittweger" },
      { round: 11, home: "ARG De Schryver", away: "Hirondelle Huegaerts" },
      { round: 11, home: "ARG Hocq", away: "BBC Oldenhove" },
      { round: 11, home: "BBC Gigot", away: "Wavre Koscielniak" },
      { round: 12, home: "Bye", away: "Wavre Koscielniak" },
      { round: 12, home: "Hirondelle Huegaerts", away: "ARG Hocq" },
      { round: 12, home: "ASUB Rittweger", away: "BBC Gigot" },
      { round: 12, home: "BBC Oldenhove", away: "ARG De Schryver" },
      { round: 13, home: "ARG Hocq", away: "Bye" },
      { round: 13, home: "Wavre Koscielniak", away: "Hirondelle Huegaerts" },
      { round: 13, home: "BBC Oldenhove", away: "ASUB Rittweger" },
      { round: 13, home: "ARG De Schryver", away: "BBC Gigot" },
      { round: 14, home: "Bye", away: "BBC Gigot" },
      { round: 14, home: "Hirondelle Huegaerts", away: "ASUB Rittweger" },
      { round: 14, home: "ARG Hocq", away: "ARG De Schryver" },
      { round: 14, home: "Wavre Koscielniak", away: "BBC Oldenhove" },
    ],
  },
  {
    name: "APM 1",
    divisionLevelCode: "third",
    teams: [
      "Smohain",
      "WBC Ramaekers",
      "ARG Vandendries",
      "BBC Roosels",
      "BNPPF Duhoux",
    ],
    roundRobinCount: 3,
    roundCount: 15,
    rounds: [
      { round: 1, date: "2026-10-06", time: "14:00" },
      { round: 2, date: "2026-10-13", time: "14:00" },
      { round: 3, date: "2026-11-03", time: "14:00" },
      { round: 4, date: "2026-11-10", time: "14:00" },
      { round: 5, date: "2026-11-17", time: "14:00" },
      { round: 6, date: "2026-12-01", time: "14:00" },
      { round: 7, date: "2026-12-08", time: "14:00" },
      { round: 8, date: "2027-01-05", time: "14:00" },
      { round: 9, date: "2027-01-12", time: "14:00" },
      { round: 10, date: "2027-01-19", time: "14:00" },
      { round: 11, date: "2027-02-09", time: "14:00" },
      { round: 12, date: "2027-02-16", time: "14:00" },
      { round: 13, date: "2027-02-23", time: "14:00" },
      { round: 14, date: "2027-03-09", time: "14:00" },
      { round: 15, date: "2027-03-16", time: "14:00" },
    ],
    fixtures: [
      { round: 1, home: "Bye", away: "Smohain" },
      { round: 1, home: "WBC Ramaekers", away: "ARG Vandendries" },
      { round: 1, home: "BBC Roosels", away: "BNPPF Duhoux" },
      { round: 2, home: "ARG Vandendries", away: "Bye" },
      { round: 2, home: "Smohain", away: "BNPPF Duhoux" },
      { round: 2, home: "WBC Ramaekers", away: "BBC Roosels" },
      { round: 3, home: "Bye", away: "BNPPF Duhoux" },
      { round: 3, home: "ARG Vandendries", away: "BBC Roosels" },
      { round: 3, home: "Smohain", away: "WBC Ramaekers" },
      { round: 4, home: "BBC Roosels", away: "Bye" },
      { round: 4, home: "BNPPF Duhoux", away: "WBC Ramaekers" },
      { round: 4, home: "ARG Vandendries", away: "Smohain" },
      { round: 5, home: "WBC Ramaekers", away: "Bye" },
      { round: 5, home: "BBC Roosels", away: "Smohain" },
      { round: 5, home: "BNPPF Duhoux", away: "ARG Vandendries" },
      { round: 6, home: "Smohain", away: "Bye" },
      { round: 6, home: "ARG Vandendries", away: "WBC Ramaekers" },
      { round: 6, home: "BNPPF Duhoux", away: "BBC Roosels" },
      { round: 7, home: "Bye", away: "ARG Vandendries" },
      { round: 7, home: "BNPPF Duhoux", away: "Smohain" },
      { round: 7, home: "BBC Roosels", away: "WBC Ramaekers" },
      { round: 8, home: "BNPPF Duhoux", away: "Bye" },
      { round: 8, home: "BBC Roosels", away: "ARG Vandendries" },
      { round: 8, home: "WBC Ramaekers", away: "Smohain" },
      { round: 9, home: "Bye", away: "BBC Roosels" },
      { round: 9, home: "WBC Ramaekers", away: "BNPPF Duhoux" },
      { round: 9, home: "Smohain", away: "ARG Vandendries" },
      { round: 10, home: "WBC Ramaekers", away: "Bye" },
      { round: 10, home: "Smohain", away: "BBC Roosels" },
      { round: 10, home: "ARG Vandendries", away: "BNPPF Duhoux" },
      { round: 11, home: "Bye", away: "Smohain" },
      { round: 11, home: "WBC Ramaekers", away: "ARG Vandendries" },
      { round: 11, home: "BBC Roosels", away: "BNPPF Duhoux" },
      { round: 12, home: "ARG Vandendries", away: "Bye" },
      { round: 12, home: "Smohain", away: "BNPPF Duhoux" },
      { round: 12, home: "WBC Ramaekers", away: "BBC Roosels" },
      { round: 13, home: "Bye", away: "BNPPF Duhoux" },
      { round: 13, home: "ARG Vandendries", away: "BBC Roosels" },
      { round: 13, home: "Smohain", away: "WBC Ramaekers" },
      { round: 14, home: "BBC Roosels", away: "Bye" },
      { round: 14, home: "BNPPF Duhoux", away: "WBC Ramaekers" },
      { round: 14, home: "ARG Vandendries", away: "Smohain" },
      { round: 15, home: "Bye", away: "WBC Ramaekers" },
      { round: 15, home: "BBC Roosels", away: "Smohain" },
      { round: 15, home: "BNPPF Duhoux", away: "ARG Vandendries" },
    ],
  },
  {
    name: "APM 2",
    divisionLevelCode: "third",
    teams: [
      "7F de Bussche",
      "7F Barroy",
      "WBC Dufrasne",
      "BBC Castille",
      "BBC Ortegat",
      "BNPPF Wilbaux",
    ],
    roundRobinCount: 3,
    roundCount: 15,
    rounds: [
      { round: 1, date: "2026-10-06", time: "14:00" },
      { round: 2, date: "2026-10-13", time: "14:00" },
      { round: 3, date: "2026-11-03", time: "14:00" },
      { round: 4, date: "2026-11-10", time: "14:00" },
      { round: 5, date: "2026-11-17", time: "14:00" },
      { round: 6, date: "2026-12-01", time: "14:00" },
      { round: 7, date: "2026-12-08", time: "14:00" },
      { round: 8, date: "2027-01-05", time: "14:00" },
      { round: 9, date: "2027-01-12", time: "14:00" },
      { round: 10, date: "2027-01-19", time: "14:00" },
      { round: 11, date: "2027-02-09", time: "14:00" },
      { round: 12, date: "2027-02-16", time: "14:00" },
      { round: 13, date: "2027-02-23", time: "14:00" },
      { round: 14, date: "2027-03-09", time: "14:00" },
      { round: 15, date: "2027-03-16", time: "14:00" },
    ],
    fixtures: [
      { round: 1, home: "7F de Bussche", away: "7F Barroy" },
      { round: 1, home: "WBC Dufrasne", away: "BBC Castille" },
      { round: 1, home: "BBC Ortegat", away: "BNPPF Wilbaux" },
      { round: 2, home: "7F de Bussche", away: "BBC Castille" },
      { round: 2, home: "7F Barroy", away: "BNPPF Wilbaux" },
      { round: 2, home: "WBC Dufrasne", away: "BBC Ortegat" },
      { round: 3, home: "7F de Bussche", away: "BNPPF Wilbaux" },
      { round: 3, home: "BBC Castille", away: "BBC Ortegat" },
      { round: 3, home: "7F Barroy", away: "WBC Dufrasne" },
      { round: 4, home: "BBC Ortegat", away: "7F de Bussche" },
      { round: 4, home: "BNPPF Wilbaux", away: "WBC Dufrasne" },
      { round: 4, home: "BBC Castille", away: "7F Barroy" },
      { round: 5, home: "WBC Dufrasne", away: "7F de Bussche" },
      { round: 5, home: "BBC Ortegat", away: "7F Barroy" },
      { round: 5, home: "BNPPF Wilbaux", away: "BBC Castille" },
      { round: 6, home: "7F Barroy", away: "7F de Bussche" },
      { round: 6, home: "BBC Castille", away: "WBC Dufrasne" },
      { round: 6, home: "BNPPF Wilbaux", away: "BBC Ortegat" },
      { round: 7, home: "BBC Castille", away: "7F de Bussche" },
      { round: 7, home: "BNPPF Wilbaux", away: "7F Barroy" },
      { round: 7, home: "BBC Ortegat", away: "WBC Dufrasne" },
      { round: 8, home: "BNPPF Wilbaux", away: "7F de Bussche" },
      { round: 8, home: "BBC Ortegat", away: "BBC Castille" },
      { round: 8, home: "WBC Dufrasne", away: "7F Barroy" },
      { round: 9, home: "7F de Bussche", away: "BBC Ortegat" },
      { round: 9, home: "WBC Dufrasne", away: "BNPPF Wilbaux" },
      { round: 9, home: "7F Barroy", away: "BBC Castille" },
      { round: 10, home: "7F de Bussche", away: "WBC Dufrasne" },
      { round: 10, home: "7F Barroy", away: "BBC Ortegat" },
      { round: 10, home: "BBC Castille", away: "BNPPF Wilbaux" },
      { round: 11, home: "7F de Bussche", away: "7F Barroy" },
      { round: 11, home: "WBC Dufrasne", away: "BBC Castille" },
      { round: 11, home: "BBC Ortegat", away: "BNPPF Wilbaux" },
      { round: 12, home: "7F de Bussche", away: "BBC Castille" },
      { round: 12, home: "7F Barroy", away: "BNPPF Wilbaux" },
      { round: 12, home: "WBC Dufrasne", away: "BBC Ortegat" },
      { round: 13, home: "7F de Bussche", away: "BNPPF Wilbaux" },
      { round: 13, home: "BBC Castille", away: "BBC Ortegat" },
      { round: 13, home: "7F Barroy", away: "WBC Dufrasne" },
      { round: 14, home: "BBC Ortegat", away: "7F de Bussche" },
      { round: 14, home: "BNPPF Wilbaux", away: "WBC Dufrasne" },
      { round: 14, home: "BBC Castille", away: "7F Barroy" },
      { round: 15, home: "WBC Dufrasne", away: "7F de Bussche" },
      { round: 15, home: "BBC Ortegat", away: "7F Barroy" },
      { round: 15, home: "BNPPF Wilbaux", away: "BBC Castille" },
    ],
  },
];

